channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - nextflow=21.04.0
    - bioconductor-biocparallel=1.26
    - bioconductor-delayedmatrixstats=1.14.0
    - bioconductor-mast=1.18.0
    - bioconductor-slingshot=2.0.0
    - bioconductor-tradeseq=1.6.0
    - r-cowplot=1.1.1
    - r-ggplot2=3.3.3
    - r-hdf5r=1.3.3
    - r-htmltools=0.5.2
    - r-kableextra=1.3.4
    - r-remotes=2.4.0
    - r-seurat=4.0.2
    - r-tidyverse=1.3.1
