channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:

    # Command-line packages
    - salmon=1.4.0

    # Languages
    - nextflow=20.04.1
    - python=3.6.12
    - r-base=3.6

    # R packages
    - bioconductor-alevinQC=1.2.0
    - bioconductor-fishpond=1.2.0
    - bioconductor-mast=1.12.0
    - bioconductor-tximport=1.14.0
    - r-argparse=2.0.3
    - r-cowplot=1.1.1
    - r-seurat=3.2.3
    - r-tidyverse=1.3.0

    # Python packages
    - argparse=1.4.0
    - elementpath=2.1.3
