channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:

    # Command-line packages
    - salmon=1.4.0

    # Languages
    - nextflow=20.04.1
    - python=3.6.12
    - r-base=4.0.3

    # R packages
    - bioconductor-alevinQC=1.6.1
    - bioconductor-fishpond=1.6.0
    - bioconductor-mast=1.16.0
    - bioconductor-slingshot=1.8.0
    - bioconductor-tximport=1.18.0
    - r-argparse=2.0.3
    - r-cowplot=1.1.1
    - r-kableextra
    - r-languageserver=0.3.12
    - r-magick=2.7.3
    - r-seurat=4.0.1
    - r-seuratobject=4.0.1
    - r-spatstat=2.1
    - r-tidyverse=1.3.0
    - r-viridis=0.6.2

    # Python packages
    - argparse=1.4.0
    - elementpath=2.1.3
